// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.hakilisoft.asuivre.operations.domain;

import com.hakilisoft.asuivre.operations.domain.OATenant;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect OATenant_Roo_Configurable {
    
    declare @type: OATenant: @Configurable;
    
}
